services:
  - type: web
    name: tb-radiology-app
    env: python
    buildCommand: pip install -r requirements.txt
    # Use ${PORT} here so Render injects the correct port at deploy time
    startCommand: uvicorn main:app --host 0.0.0.0 --port ${PORT}
    # Optional: tell Render which path to hit for health checks
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
    region: oregon
